//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::domain::types::UserId;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "jwt_refresh_storage")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub refresh_token_hash: i64,
    pub user_id: UserId,
    pub expiry_date: chrono::NaiveDateTime,
    pub mfa: i64,
    /// What minted this refresh token: "session" for an interactive login,
    /// "app-cli" for a credential derived for an app. Kinds other than
    /// "session" are revoked individually rather than with the user's other
    /// sessions.
    pub kind: String,
    /// Free-form provenance for non-session kinds, e.g. "app:lares:alice".
    pub label: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::UserId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
